version: 2
updates:
  # Monitor GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
    assignees:
      - yamatt
    labels:
      - dependabot
      - docker

  # Monitor Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - yamatt
    labels:
      - dependabot
      - docker
